language: java
sudo: required
dist: trusty
group: edge

addons:
  sonarcloud:
    organization: trellis-ldp

services:
  - mysql

before_script:
  - psql -c 'create database trellis;' -U postgres
  - mysql -e 'CREATE DATABASE trellis;'

matrix:
  fast_finish: true

  include:
    # JDK 8
    - jdk: oraclejdk8
      after_success: ./gradlew jacocoRootReport coveralls sonarqube

    # JDK 11
    - jdk: oraclejdk11

script: ./gradlew clean check install
